// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diskusiPR.Models;

public partial class JenjangPendidikan
{
    public int IdJenjangPendidikan { get; set; }

    public string NamaJenjang { get; set; }

    public virtual ICollection<Soal> Soals { get; set; } = new List<Soal>();
}