// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diskusiPR.Models;

public partial class MataPelajaran
{
    public int IdMataPelajaran { get; set; }

    public string NamaMapel { get; set; }

    public int? IdSubMapel { get; set; }

    public virtual SubMataPelajaran IdSubMapelNavigation { get; set; }

    public virtual ICollection<Soal> Soals { get; set; } = new List<Soal>();
}