// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diskusiPR.Models;

public partial class Soal
{
    public int IdSoal { get; set; }

    public string Foto { get; set; }

    public string Soal1 { get; set; }

    public int Author { get; set; }

    public int IdMataPelajaran { get; set; }

    public int IdJenjangPendidikan { get; set; }

    public virtual User AuthorNavigation { get; set; }

    public virtual JenjangPendidikan IdJenjangPendidikanNavigation { get; set; }

    public virtual MataPelajaran IdMataPelajaranNavigation { get; set; }

    public virtual ICollection<SoalJawaban> SoalJawabans { get; set; } = new List<SoalJawaban>();
}