// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diskusiPR.Models;

public partial class SoalJawaban
{
    public int IdSoalJawaban { get; set; }

    public int IdSoal { get; set; }

    public int IdJawaban { get; set; }

    public virtual Jawaban IdJawabanNavigation { get; set; }

    public virtual Soal IdSoalNavigation { get; set; }
}