// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace diskusiPR.Models;

public partial class SubMataPelajaran
{
    public int IdSubMapel { get; set; }

    public string NamaSubMapel { get; set; }

    public virtual ICollection<MataPelajaran> MataPelajarans { get; set; } = new List<MataPelajaran>();
}